In [1]:
import numpy as np

In [2]:
# All 0 matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# All 1 matrix
np.ones((2,3,4,5), dtype="int16")

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int16)

In [4]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [5]:
# Any other number (full like)
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [6]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.55117597, 0.94405842, 0.92690679, 0.24257432, 0.17779512,
        0.98037227, 0.4497123 ],
       [0.84595964, 0.37583575, 0.20084559, 0.87728887, 0.97840227,
        0.81849259, 0.52539802]])

In [7]:
# Random Integer values (startindex, endindex, size=())
np.random.randint(7, size=(3,3))

array([[0, 5, 6],
       [0, 1, 5],
       [2, 3, 2]])

In [8]:
# Identitiy matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [10]:
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [11]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [14]:
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be carefuly copying arrays!!!

In [15]:
# Same pointer location
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [16]:
# Solution
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Mathematics

In [17]:
a = np.array([1,2,3,4])

In [18]:
# Add a value to all elems
a + 2

array([3, 4, 5, 6])

In [19]:
# Subtract a vlaue from all elems
a - 2

array([-1,  0,  1,  2])

In [20]:
# Multiplicate the array by a value
a * 2

array([2, 4, 6, 8])

In [21]:
# Divide the array by a value
a / 2

array([0.5, 1. , 1.5, 2. ])

In [22]:
# Add two arrays together
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [23]:
# Square the elems of an array
a ** 2

array([ 1,  4,  9, 16])

In [24]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [25]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Lineare Algebra

In [30]:
# Matrix multiplikation
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [34]:
# Determinante einer Matrix
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [35]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# Minimum
np.min(stats)

1

In [37]:
# Maximum
np.max(stats)

6

In [40]:
# Minimum on a axis
np.min(stats, axis=1)

array([1, 4])

In [41]:
# Add all values
np.sum(stats)

21

In [42]:
# Add all values of an axis
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing Arrays

In [48]:
# Reshaping
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [51]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [56]:
# Horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load Data from File

In [68]:
filedata = np.genfromtxt("data.txt", delimiter=",")
filedata = filedata.astype("int32")

### Boolean Masking and Advanced Indexing

In [77]:
# Checks all elemes if they are bigger than 500
filedata > 500

array([[ True, False, False,  True,  True,  True, False,  True, False,
        False,  True,  True,  True, False, False, False, False,  True],
       [False, False, False, False, False,  True,  True, False,  True,
        False, False, False, False, False, False,  True,  True,  True],
       [False, False, False,  True,  True,  True, False, False, False,
        False,  True,  True, False, False,  True,  True,  True,  True]])

In [78]:
# get only the values which a greater than 500
filedata[filedata > 500]

array([806, 768, 789, 663, 670, 672, 906, 775, 574, 873, 774, 886, 872,
       730, 849, 778, 661, 980, 721, 871, 888, 654, 940, 891])

In [79]:
# Which columns have a value greater than 500
np.any(filedata > 500, axis=0)

array([ True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True])

In [82]:
# Values greater than 500 and smaller than 750
((filedata > 500) & (filedata < 750))

array([[False, False, False, False, False,  True, False,  True, False,
        False,  True, False, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False],
       [False, False, False, False,  True, False, False, False, False,
        False,  True, False, False, False, False,  True, False, False]])

In [84]:
# Values not (greater than 500 and smaller than 750)
(~((filedata > 500) & (filedata < 750)))

array([[ True,  True,  True,  True,  True, False,  True, False,  True,
         True, False,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True]])

## Index with a List

In [75]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

## Exercises

In [94]:
array = np.arange(1, 31)
array_6x5 = np.reshape(array, (6,5))
array_6x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [99]:
# Teilmatrix selektieren
array_6x5[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [102]:
# Diagonal
array_6x5[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [105]:
# Teilmatrix über auseinanderhängende rows
array_6x5[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])